modLoader = "kotori_scala"
loaderVersion = "[2.13.8,2.14.0)"
issueTrackerURL = "https://github.com/bdew-minecraft/proxy/issues"
license = "MIT"

[[mods]]
modId = "proxy"
version = "${file.jarVersion}"
displayName = "Proxy"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/proxy"
authors = "bdew"
description = '''
This mod adds a single block, called a Proxy, which allows remotely accessing other block's inventories, fluid tanks, energy storage (Forge or Tesla) and anything else exposed as Forge capabilities. This works at any range and even from other dimensions.
After crafting a proxy block you can shift+right click it on any block or machine to bind it to the location, then you place the proxy block elsewhere and can use it to access the block it's bound to.
'''

[[dependencies.compacter]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compacter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compacter]]
modId = "bdlib"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

